/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Event {
  'id' : string,
  'owner' : Principal,
  'time' : bigint,
  'description' : string,
  'needs' : Array<string>,
  'image' : [] | [string],
  'creatorProfileId' : string,
  'location' : string,
}
export interface EventInput {
  'id' : string,
  'time' : bigint,
  'description' : string,
  'needs' : Array<string>,
  'image' : [] | [string],
  'creatorProfileId' : string,
  'location' : string,
}
export type FunctionType = { 'production' : null } |
  { 'education' : null } |
  { 'equipmentSpace' : null } |
  { 'wasteManagement' : null } |
  { 'processing' : null } |
  { 'distribution' : null };
export interface JoinRequest {
  'status' : JoinRequestStatus,
  'principal' : Principal,
  'displayName' : [] | [string],
  'profileId' : string,
}
export type JoinRequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface Need {
  'id' : string,
  'endDate' : bigint,
  'owner' : Principal,
  'profileId' : string,
  'description' : string,
  'category' : ResourceCategory,
  'startDate' : bigint,
}
export interface NeedInput {
  'id' : string,
  'endDate' : bigint,
  'profileId' : string,
  'description' : string,
  'category' : ResourceCategory,
  'startDate' : bigint,
}
export interface Profile {
  'id' : string,
  'bio' : [] | [string],
  'organizationName' : string,
  'owner' : Principal,
  'resources' : Array<string>,
  'email' : string,
  'needs' : Array<string>,
  'address' : [] | [string],
  'functions' : Array<FunctionType>,
  'phone' : [] | [string],
  'profilePicture' : [] | [string],
}
export interface ProfileMember {
  'principal' : Principal,
  'displayName' : [] | [string],
  'role' : ProfileRole,
}
export type ProfileRole = { 'user' : null } |
  { 'clubAdmin' : null };
export interface RegistrationData {
  'id' : string,
  'bio' : [] | [string],
  'organizationName' : string,
  'email' : string,
  'address' : [] | [string],
  'functions' : Array<FunctionType>,
  'phone' : [] | [string],
  'profilePicture' : [] | [string],
}
export type ResourceCategory = { 'storageSpace' : null } |
  { 'other' : null } |
  { 'equipment' : null } |
  { 'publicity' : null } |
  { 'foodDrink' : null } |
  { 'distributionSpace' : null } |
  { 'kitchenSpace' : null };
export interface ResourceHave {
  'id' : string,
  'owner' : Principal,
  'profileId' : string,
  'description' : string,
  'category' : ResourceCategory,
}
export interface ResourceInput {
  'id' : string,
  'profileId' : string,
  'description' : string,
  'category' : ResourceCategory,
}
export interface SuspensionInfo {
  'suspendedAt' : bigint,
  'suspendedBy' : Principal,
  'reason' : string,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'profileId' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhitelistEntry {
  'principal' : Principal,
  'timestamp' : bigint,
  'reason' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addEvent' : ActorMethod<[EventInput], Event>,
  'addMember' : ActorMethod<[string, Principal, ProfileRole], undefined>,
  'addNeed' : ActorMethod<[NeedInput], Need>,
  'addResource' : ActorMethod<[ResourceInput], ResourceHave>,
  'approveJoinRequest' : ActorMethod<[string, Principal, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteNeed' : ActorMethod<[string], undefined>,
  'deleteProfile' : ActorMethod<[string], undefined>,
  'deleteResource' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisplayName' : ActorMethod<[], [] | [string]>,
  'getGlobalMatches' : ActorMethod<[], Array<[Need, Array<ResourceHave>]>>,
  'getMatches' : ActorMethod<[string], Array<[Need, Array<ResourceHave>]>>,
  'getProfile' : ActorMethod<[string], [] | [Profile]>,
  'getSuspensionInfo' : ActorMethod<[Principal], [] | [SuspensionInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isSuspendedUser' : ActorMethod<[Principal], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listHistoricalWhitelist' : ActorMethod<[], Array<WhitelistEntry>>,
  'listJoinRequests' : ActorMethod<[string], Array<JoinRequest>>,
  'listMembers' : ActorMethod<[string], Array<ProfileMember>>,
  'listNeeds' : ActorMethod<[], Array<Need>>,
  'listProfiles' : ActorMethod<[], Array<Profile>>,
  'listResources' : ActorMethod<[], Array<ResourceHave>>,
  'listSuspendedUsers' : ActorMethod<[], Array<SuspensionInfo>>,
  'registerProfile' : ActorMethod<[RegistrationData], Profile>,
  'removeMember' : ActorMethod<[string, Principal], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestJoin' : ActorMethod<[string, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'suspendUser' : ActorMethod<[Principal, string], undefined>,
  'unsuspendUser' : ActorMethod<[Principal], undefined>,
  'updateProfile' : ActorMethod<[string, RegistrationData], Profile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];