/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EventInput = IDL.Record({
  'id' : IDL.Text,
  'time' : IDL.Int,
  'description' : IDL.Text,
  'needs' : IDL.Vec(IDL.Text),
  'image' : IDL.Opt(IDL.Text),
  'creatorProfileId' : IDL.Text,
  'location' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'time' : IDL.Int,
  'description' : IDL.Text,
  'needs' : IDL.Vec(IDL.Text),
  'image' : IDL.Opt(IDL.Text),
  'creatorProfileId' : IDL.Text,
  'location' : IDL.Text,
});
export const ProfileRole = IDL.Variant({
  'user' : IDL.Null,
  'clubAdmin' : IDL.Null,
});
export const ResourceCategory = IDL.Variant({
  'storageSpace' : IDL.Null,
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'publicity' : IDL.Null,
  'foodDrink' : IDL.Null,
  'distributionSpace' : IDL.Null,
  'kitchenSpace' : IDL.Null,
});
export const NeedInput = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Int,
  'profileId' : IDL.Text,
  'description' : IDL.Text,
  'category' : ResourceCategory,
  'startDate' : IDL.Int,
});
export const Need = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Int,
  'owner' : IDL.Principal,
  'profileId' : IDL.Text,
  'description' : IDL.Text,
  'category' : ResourceCategory,
  'startDate' : IDL.Int,
});
export const ResourceInput = IDL.Record({
  'id' : IDL.Text,
  'profileId' : IDL.Text,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const ResourceHave = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'profileId' : IDL.Text,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'profileId' : IDL.Text });
export const FunctionType = IDL.Variant({
  'production' : IDL.Null,
  'education' : IDL.Null,
  'equipmentSpace' : IDL.Null,
  'wasteManagement' : IDL.Null,
  'processing' : IDL.Null,
  'distribution' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Opt(IDL.Text),
  'organizationName' : IDL.Text,
  'owner' : IDL.Principal,
  'resources' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'needs' : IDL.Vec(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'functions' : IDL.Vec(FunctionType),
  'phone' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(IDL.Text),
});
export const SuspensionInfo = IDL.Record({
  'suspendedAt' : IDL.Int,
  'suspendedBy' : IDL.Principal,
  'reason' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const WhitelistEntry = IDL.Record({
  'principal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const JoinRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const JoinRequest = IDL.Record({
  'status' : JoinRequestStatus,
  'principal' : IDL.Principal,
  'displayName' : IDL.Opt(IDL.Text),
  'profileId' : IDL.Text,
});
export const ProfileMember = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Opt(IDL.Text),
  'role' : ProfileRole,
});
export const RegistrationData = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Opt(IDL.Text),
  'organizationName' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'functions' : IDL.Vec(FunctionType),
  'phone' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addEvent' : IDL.Func([EventInput], [Event], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Principal, ProfileRole], [], []),
  'addNeed' : IDL.Func([NeedInput], [Need], []),
  'addResource' : IDL.Func([ResourceInput], [ResourceHave], []),
  'approveJoinRequest' : IDL.Func([IDL.Text, IDL.Principal, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteNeed' : IDL.Func([IDL.Text], [], []),
  'deleteProfile' : IDL.Func([IDL.Text], [], []),
  'deleteResource' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getGlobalMatches' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Need, IDL.Vec(ResourceHave)))],
      ['query'],
    ),
  'getMatches' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Need, IDL.Vec(ResourceHave)))],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getSuspensionInfo' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SuspensionInfo)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isSuspendedUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listHistoricalWhitelist' : IDL.Func(
      [],
      [IDL.Vec(WhitelistEntry)],
      ['query'],
    ),
  'listJoinRequests' : IDL.Func([IDL.Text], [IDL.Vec(JoinRequest)], ['query']),
  'listMembers' : IDL.Func([IDL.Text], [IDL.Vec(ProfileMember)], ['query']),
  'listNeeds' : IDL.Func([], [IDL.Vec(Need)], ['query']),
  'listProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'listResources' : IDL.Func([], [IDL.Vec(ResourceHave)], ['query']),
  'listSuspendedUsers' : IDL.Func([], [IDL.Vec(SuspensionInfo)], ['query']),
  'registerProfile' : IDL.Func([RegistrationData], [Profile], []),
  'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestJoin' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'suspendUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'unsuspendUser' : IDL.Func([IDL.Principal], [], []),
  'updateProfile' : IDL.Func([IDL.Text, RegistrationData], [Profile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EventInput = IDL.Record({
    'id' : IDL.Text,
    'time' : IDL.Int,
    'description' : IDL.Text,
    'needs' : IDL.Vec(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
    'creatorProfileId' : IDL.Text,
    'location' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'time' : IDL.Int,
    'description' : IDL.Text,
    'needs' : IDL.Vec(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
    'creatorProfileId' : IDL.Text,
    'location' : IDL.Text,
  });
  const ProfileRole = IDL.Variant({
    'user' : IDL.Null,
    'clubAdmin' : IDL.Null,
  });
  const ResourceCategory = IDL.Variant({
    'storageSpace' : IDL.Null,
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'publicity' : IDL.Null,
    'foodDrink' : IDL.Null,
    'distributionSpace' : IDL.Null,
    'kitchenSpace' : IDL.Null,
  });
  const NeedInput = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Int,
    'profileId' : IDL.Text,
    'description' : IDL.Text,
    'category' : ResourceCategory,
    'startDate' : IDL.Int,
  });
  const Need = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Int,
    'owner' : IDL.Principal,
    'profileId' : IDL.Text,
    'description' : IDL.Text,
    'category' : ResourceCategory,
    'startDate' : IDL.Int,
  });
  const ResourceInput = IDL.Record({
    'id' : IDL.Text,
    'profileId' : IDL.Text,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const ResourceHave = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'profileId' : IDL.Text,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'profileId' : IDL.Text });
  const FunctionType = IDL.Variant({
    'production' : IDL.Null,
    'education' : IDL.Null,
    'equipmentSpace' : IDL.Null,
    'wasteManagement' : IDL.Null,
    'processing' : IDL.Null,
    'distribution' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Opt(IDL.Text),
    'organizationName' : IDL.Text,
    'owner' : IDL.Principal,
    'resources' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'needs' : IDL.Vec(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'functions' : IDL.Vec(FunctionType),
    'phone' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(IDL.Text),
  });
  const SuspensionInfo = IDL.Record({
    'suspendedAt' : IDL.Int,
    'suspendedBy' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const WhitelistEntry = IDL.Record({
    'principal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const JoinRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const JoinRequest = IDL.Record({
    'status' : JoinRequestStatus,
    'principal' : IDL.Principal,
    'displayName' : IDL.Opt(IDL.Text),
    'profileId' : IDL.Text,
  });
  const ProfileMember = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Opt(IDL.Text),
    'role' : ProfileRole,
  });
  const RegistrationData = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Opt(IDL.Text),
    'organizationName' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'functions' : IDL.Vec(FunctionType),
    'phone' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addEvent' : IDL.Func([EventInput], [Event], []),
    'addMember' : IDL.Func([IDL.Text, IDL.Principal, ProfileRole], [], []),
    'addNeed' : IDL.Func([NeedInput], [Need], []),
    'addResource' : IDL.Func([ResourceInput], [ResourceHave], []),
    'approveJoinRequest' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Bool],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteNeed' : IDL.Func([IDL.Text], [], []),
    'deleteProfile' : IDL.Func([IDL.Text], [], []),
    'deleteResource' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getGlobalMatches' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Need, IDL.Vec(ResourceHave)))],
        ['query'],
      ),
    'getMatches' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Need, IDL.Vec(ResourceHave)))],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'getSuspensionInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SuspensionInfo)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isSuspendedUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listHistoricalWhitelist' : IDL.Func(
        [],
        [IDL.Vec(WhitelistEntry)],
        ['query'],
      ),
    'listJoinRequests' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JoinRequest)],
        ['query'],
      ),
    'listMembers' : IDL.Func([IDL.Text], [IDL.Vec(ProfileMember)], ['query']),
    'listNeeds' : IDL.Func([], [IDL.Vec(Need)], ['query']),
    'listProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'listResources' : IDL.Func([], [IDL.Vec(ResourceHave)], ['query']),
    'listSuspendedUsers' : IDL.Func([], [IDL.Vec(SuspensionInfo)], ['query']),
    'registerProfile' : IDL.Func([RegistrationData], [Profile], []),
    'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestJoin' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'suspendUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'unsuspendUser' : IDL.Func([IDL.Principal], [], []),
    'updateProfile' : IDL.Func([IDL.Text, RegistrationData], [Profile], []),
  });
};

export const init = ({ IDL }) => { return []; };