/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResourceInput {
    id: string;
    profileId: string;
    description: string;
    category: ResourceCategory;
}
export interface JoinRequest {
    status: JoinRequestStatus;
    principal: Principal;
    displayName?: string;
    profileId: string;
}
export interface WhitelistEntry {
    principal: Principal;
    timestamp: bigint;
    reason: string;
}
export interface Need {
    id: string;
    endDate: bigint;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
    startDate: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    id: string;
    owner: Principal;
    time: bigint;
    description: string;
    needs: Array<string>;
    image?: string;
    creatorProfileId: string;
    location: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SuspensionInfo {
    suspendedAt: bigint;
    suspendedBy: Principal;
    reason: string;
}
export interface Profile {
    id: string;
    bio?: string;
    organizationName: string;
    owner: Principal;
    resources: Array<string>;
    email: string;
    needs: Array<string>;
    address?: string;
    functions: Array<FunctionType>;
    phone?: string;
    profilePicture?: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface ResourceHave {
    id: string;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
}
export interface EventInput {
    id: string;
    time: bigint;
    description: string;
    needs: Array<string>;
    image?: string;
    creatorProfileId: string;
    location: string;
}
export interface RegistrationData {
    id: string;
    bio?: string;
    organizationName: string;
    email: string;
    address?: string;
    functions: Array<FunctionType>;
    phone?: string;
    profilePicture?: string;
}
export interface ProfileMember {
    principal: Principal;
    displayName?: string;
    role: ProfileRole;
}
export interface NeedInput {
    id: string;
    endDate: bigint;
    profileId: string;
    description: string;
    category: ResourceCategory;
    startDate: bigint;
}
export interface UserProfile {
    profileId: string;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum FunctionType {
    production = "production",
    education = "education",
    equipmentSpace = "equipmentSpace",
    wasteManagement = "wasteManagement",
    processing = "processing",
    distribution = "distribution"
}
export enum JoinRequestStatus {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum ProfileRole {
    user = "user",
    clubAdmin = "clubAdmin"
}
export enum ResourceCategory {
    storageSpace = "storageSpace",
    other = "other",
    equipment = "equipment",
    publicity = "publicity",
    foodDrink = "foodDrink",
    distributionSpace = "distributionSpace",
    kitchenSpace = "kitchenSpace"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addEvent(input: EventInput): Promise<Event>;
    addMember(profileId: string, memberPrincipal: Principal, role: ProfileRole): Promise<void>;
    addNeed(input: NeedInput): Promise<Need>;
    addResource(input: ResourceInput): Promise<ResourceHave>;
    approveJoinRequest(profileId: string, requestorPrincipal: Principal, approved: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    deleteNeed(id: string): Promise<void>;
    deleteProfile(id: string): Promise<void>;
    deleteResource(id: string): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDisplayName(): Promise<string | null>;
    getGlobalMatches(): Promise<Array<[Need, Array<ResourceHave>]>>;
    getMatches(profileId: string): Promise<Array<[Need, Array<ResourceHave>]>>;
    getProfile(id: string): Promise<Profile | null>;
    getSuspensionInfo(user: Principal): Promise<SuspensionInfo | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isSuspendedUser(user: Principal): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listEvents(): Promise<Array<Event>>;
    listHistoricalWhitelist(): Promise<Array<WhitelistEntry>>;
    listJoinRequests(profileId: string): Promise<Array<JoinRequest>>;
    listMembers(profileId: string): Promise<Array<ProfileMember>>;
    listNeeds(): Promise<Array<Need>>;
    listProfiles(): Promise<Array<Profile>>;
    listResources(): Promise<Array<ResourceHave>>;
    listSuspendedUsers(): Promise<Array<SuspensionInfo>>;
    registerProfile(registrationData: RegistrationData): Promise<Profile>;
    removeMember(profileId: string, memberPrincipal: Principal): Promise<void>;
    requestApproval(): Promise<void>;
    requestJoin(profileId: string, displayName: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setDisplayName(name: string): Promise<void>;
    suspendUser(user: Principal, reason: string): Promise<void>;
    unsuspendUser(user: Principal): Promise<void>;
    updateProfile(id: string, data: RegistrationData): Promise<Profile>;
}
import type { ApprovalStatus as _ApprovalStatus, Event as _Event, EventInput as _EventInput, FunctionType as _FunctionType, JoinRequest as _JoinRequest, JoinRequestStatus as _JoinRequestStatus, Need as _Need, NeedInput as _NeedInput, Profile as _Profile, ProfileMember as _ProfileMember, ProfileRole as _ProfileRole, RegistrationData as _RegistrationData, ResourceCategory as _ResourceCategory, ResourceHave as _ResourceHave, ResourceInput as _ResourceInput, SuspensionInfo as _SuspensionInfo, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addEvent(arg0: EventInput): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(to_candid_EventInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Event_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(to_candid_EventInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Event_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMember(arg0: string, arg1: Principal, arg2: ProfileRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, arg1, to_candid_ProfileRole_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, arg1, to_candid_ProfileRole_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addNeed(arg0: NeedInput): Promise<Need> {
        if (this.processError) {
            try {
                const result = await this.actor.addNeed(to_candid_NeedInput_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Need_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNeed(to_candid_NeedInput_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Need_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async addResource(arg0: ResourceInput): Promise<ResourceHave> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(to_candid_ResourceInput_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResourceHave_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(to_candid_ResourceInput_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResourceHave_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveJoinRequest(arg0: string, arg1: Principal, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJoinRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJoinRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteNeed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNeed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNeed(arg0);
            return result;
        }
    }
    async deleteProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile(arg0);
            return result;
        }
    }
    async deleteResource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDisplayName(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisplayName();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisplayName();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalMatches(): Promise<Array<[Need, Array<ResourceHave>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalMatches();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalMatches();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(arg0: string): Promise<Array<[Need, Array<ResourceHave>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuspensionInfo(arg0: Principal): Promise<SuspensionInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuspensionInfo(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuspensionInfo(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isSuspendedUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSuspendedUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSuspendedUser(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHistoricalWhitelist(): Promise<Array<WhitelistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHistoricalWhitelist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHistoricalWhitelist();
            return result;
        }
    }
    async listJoinRequests(arg0: string): Promise<Array<JoinRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJoinRequests(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJoinRequests(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMembers(arg0: string): Promise<Array<ProfileMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMembers(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMembers(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNeeds(): Promise<Array<Need>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNeeds();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNeeds();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProfiles();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProfiles();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResources(): Promise<Array<ResourceHave>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResources();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResources();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSuspendedUsers(): Promise<Array<SuspensionInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuspendedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuspendedUsers();
            return result;
        }
    }
    async registerProfile(arg0: RegistrationData): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(to_candid_RegistrationData_n60(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Profile_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(to_candid_RegistrationData_n60(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Profile_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0, arg1);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async requestJoin(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestJoin(arg0, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestJoin(arg0, to_candid_opt_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDisplayName(arg0);
            return result;
        }
    }
    async suspendUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0, arg1);
            return result;
        }
    }
    async unsuspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsuspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsuspendUser(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: RegistrationData): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, to_candid_RegistrationData_n60(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Profile_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, to_candid_RegistrationData_n60(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Profile_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApprovalStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_FunctionType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FunctionType): FunctionType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_JoinRequestStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinRequestStatus): JoinRequestStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_JoinRequest_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinRequest): JoinRequest {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Need_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Need): Need {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileMember_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileMember): ProfileMember {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileRole): ProfileRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceHave_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceHave): ResourceHave {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SuspensionInfo]): SuspensionInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    time: bigint;
    description: string;
    needs: Array<string>;
    image: [] | [string];
    creatorProfileId: string;
    location: string;
}): {
    id: string;
    owner: Principal;
    time: bigint;
    description: string;
    needs: Array<string>;
    image?: string;
    creatorProfileId: string;
    location: string;
} {
    return {
        id: value.id,
        owner: value.owner,
        time: value.time,
        description: value.description,
        needs: value.needs,
        image: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.image)),
        creatorProfileId: value.creatorProfileId,
        location: value.location
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: bigint;
    owner: Principal;
    profileId: string;
    description: string;
    category: _ResourceCategory;
    startDate: bigint;
}): {
    id: string;
    endDate: bigint;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        owner: value.owner,
        profileId: value.profileId,
        description: value.description,
        category: from_candid_ResourceCategory_n21(_uploadFile, _downloadFile, value.category),
        startDate: value.startDate
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    profileId: string;
    description: string;
    category: _ResourceCategory;
}): {
    id: string;
    owner: Principal;
    profileId: string;
    description: string;
    category: ResourceCategory;
} {
    return {
        id: value.id,
        owner: value.owner,
        profileId: value.profileId,
        description: value.description,
        category: from_candid_ResourceCategory_n21(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: [] | [string];
    organizationName: string;
    owner: Principal;
    resources: Array<string>;
    email: string;
    needs: Array<string>;
    address: [] | [string];
    functions: Array<_FunctionType>;
    phone: [] | [string];
    profilePicture: [] | [string];
}): {
    id: string;
    bio?: string;
    organizationName: string;
    owner: Principal;
    resources: Array<string>;
    email: string;
    needs: Array<string>;
    address?: string;
    functions: Array<FunctionType>;
    phone?: string;
    profilePicture?: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.bio)),
        organizationName: value.organizationName,
        owner: value.owner,
        resources: value.resources,
        email: value.email,
        needs: value.needs,
        address: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.address)),
        functions: from_candid_vec_n38(_uploadFile, _downloadFile, value.functions),
        phone: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.phone)),
        profilePicture: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n45(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JoinRequestStatus;
    principal: Principal;
    displayName: [] | [string];
    profileId: string;
}): {
    status: JoinRequestStatus;
    principal: Principal;
    displayName?: string;
    profileId: string;
} {
    return {
        status: from_candid_JoinRequestStatus_n51(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        displayName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.displayName)),
        profileId: value.profileId
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: [] | [string];
    role: _ProfileRole;
}): {
    principal: Principal;
    displayName?: string;
    role: ProfileRole;
} {
    return {
        principal: value.principal,
        displayName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.displayName)),
        role: from_candid_ProfileRole_n56(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_tuple_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Need, Array<_ResourceHave>]): [Need, Array<ResourceHave>] {
    return [
        from_candid_Need_n19(_uploadFile, _downloadFile, value[0]),
        from_candid_vec_n34(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    storageSpace: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    publicity: null;
} | {
    foodDrink: null;
} | {
    distributionSpace: null;
} | {
    kitchenSpace: null;
}): ResourceCategory {
    return "storageSpace" in value ? ResourceCategory.storageSpace : "other" in value ? ResourceCategory.other : "equipment" in value ? ResourceCategory.equipment : "publicity" in value ? ResourceCategory.publicity : "foodDrink" in value ? ResourceCategory.foodDrink : "distributionSpace" in value ? ResourceCategory.distributionSpace : "kitchenSpace" in value ? ResourceCategory.kitchenSpace : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    production: null;
} | {
    education: null;
} | {
    equipmentSpace: null;
} | {
    wasteManagement: null;
} | {
    processing: null;
} | {
    distribution: null;
}): FunctionType {
    return "production" in value ? FunctionType.production : "education" in value ? FunctionType.education : "equipmentSpace" in value ? FunctionType.equipmentSpace : "wasteManagement" in value ? FunctionType.wasteManagement : "processing" in value ? FunctionType.processing : "distribution" in value ? FunctionType.distribution : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): JoinRequestStatus {
    return "pending" in value ? JoinRequestStatus.pending : "denied" in value ? JoinRequestStatus.denied : "approved" in value ? JoinRequestStatus.approved : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    clubAdmin: null;
}): ProfileRole {
    return "user" in value ? ProfileRole.user : "clubAdmin" in value ? ProfileRole.clubAdmin : value;
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Need, Array<_ResourceHave>]>): Array<[Need, Array<ResourceHave>]> {
    return value.map((x)=>from_candid_tuple_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResourceHave>): Array<ResourceHave> {
    return value.map((x)=>from_candid_ResourceHave_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FunctionType>): Array<FunctionType> {
    return value.map((x)=>from_candid_FunctionType_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JoinRequest>): Array<JoinRequest> {
    return value.map((x)=>from_candid_JoinRequest_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfileMember>): Array<ProfileMember> {
    return value.map((x)=>from_candid_ProfileMember_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Need>): Array<Need> {
    return value.map((x)=>from_candid_Need_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n36(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_EventInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventInput): _EventInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_FunctionType_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FunctionType): _FunctionType {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_NeedInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NeedInput): _NeedInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): _ProfileRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationData_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationData): _RegistrationData {
    return to_candid_record_n61(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceInput_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceInput): _ResourceInput {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: bigint;
    profileId: string;
    description: string;
    category: ResourceCategory;
    startDate: bigint;
}): {
    id: string;
    endDate: bigint;
    profileId: string;
    description: string;
    category: _ResourceCategory;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        profileId: value.profileId,
        description: value.description,
        category: to_candid_ResourceCategory_n17(_uploadFile, _downloadFile, value.category),
        startDate: value.startDate
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    profileId: string;
    description: string;
    category: ResourceCategory;
}): {
    id: string;
    profileId: string;
    description: string;
    category: _ResourceCategory;
} {
    return {
        id: value.id,
        profileId: value.profileId,
        description: value.description,
        category: to_candid_ResourceCategory_n17(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio?: string;
    organizationName: string;
    email: string;
    address?: string;
    functions: Array<FunctionType>;
    phone?: string;
    profilePicture?: string;
}): {
    id: string;
    bio: [] | [string];
    organizationName: string;
    email: string;
    address: [] | [string];
    functions: Array<_FunctionType>;
    phone: [] | [string];
    profilePicture: [] | [string];
} {
    return {
        id: value.id,
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        organizationName: value.organizationName,
        email: value.email,
        address: value.address ? candid_some(value.address) : candid_none(),
        functions: to_candid_vec_n62(_uploadFile, _downloadFile, value.functions),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    time: bigint;
    description: string;
    needs: Array<string>;
    image?: string;
    creatorProfileId: string;
    location: string;
}): {
    id: string;
    time: bigint;
    description: string;
    needs: Array<string>;
    image: [] | [string];
    creatorProfileId: string;
    location: string;
} {
    return {
        id: value.id,
        time: value.time,
        description: value.description,
        needs: value.needs,
        image: value.image ? candid_some(value.image) : candid_none(),
        creatorProfileId: value.creatorProfileId,
        location: value.location
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileRole): {
    user: null;
} | {
    clubAdmin: null;
} {
    return value == ProfileRole.user ? {
        user: null
    } : value == ProfileRole.clubAdmin ? {
        clubAdmin: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    storageSpace: null;
} | {
    other: null;
} | {
    equipment: null;
} | {
    publicity: null;
} | {
    foodDrink: null;
} | {
    distributionSpace: null;
} | {
    kitchenSpace: null;
} {
    return value == ResourceCategory.storageSpace ? {
        storageSpace: null
    } : value == ResourceCategory.other ? {
        other: null
    } : value == ResourceCategory.equipment ? {
        equipment: null
    } : value == ResourceCategory.publicity ? {
        publicity: null
    } : value == ResourceCategory.foodDrink ? {
        foodDrink: null
    } : value == ResourceCategory.distributionSpace ? {
        distributionSpace: null
    } : value == ResourceCategory.kitchenSpace ? {
        kitchenSpace: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FunctionType): {
    production: null;
} | {
    education: null;
} | {
    equipmentSpace: null;
} | {
    wasteManagement: null;
} | {
    processing: null;
} | {
    distribution: null;
} {
    return value == FunctionType.production ? {
        production: null
    } : value == FunctionType.education ? {
        education: null
    } : value == FunctionType.equipmentSpace ? {
        equipmentSpace: null
    } : value == FunctionType.wasteManagement ? {
        wasteManagement: null
    } : value == FunctionType.processing ? {
        processing: null
    } : value == FunctionType.distribution ? {
        distribution: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FunctionType>): Array<_FunctionType> {
    return value.map((x)=>to_candid_FunctionType_n63(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
